version: "2"

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: "MYSQL"
    hostname: mysql
    restart: always
    networks:
      whmcs:
        ipv4_address: 10.0.1.2
    environment:
      MYSQL_HOST: "127.0.0.1"
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_ROOT_HOST: '%'
      SMTP_HOST: 10.0.1.221
      SMTP_PORT: 1025
    ports:
      - 3306:3306

  whmcs:
    image: fauzie/docker-whmcs:latest
    container_name: "WHMCS"
    hostname: cp.dynamic.com
    networks:
      whmcs:
        ipv4_address: 10.0.1.3
    restart: always
    depends_on:
      - mysql
    environment:
      WORKER_PROCESSES: 4
      VIRTUAL_HOST: cp.dynamic.com
      APP_PASSWORD: userapppassword
      WHMCS_SERVER_IP: 10.0.1.104
      HTTPS: "on"
    ports:
      - 80:80
      - 2222:2222
    volumes:
      - /Applications/MAMP/htdocs/upwork/cloudportal/PORTAL_WHMCS/virtuals.conf:/etc/nginx/conf.d/virtuals.conf
      - /Applications/MAMP/htdocs/upwork/cloudportal/PORTAL_WHMCS/php-fpm.conf:/etc/php/7.3/fpm/php-fpm.conf
      - /Applications/MAMP/htdocs/upwork/cloudportal/PORTAL_WHMCS/non-public:/virtual/cp.dynamic.com/htdocs/non-public
      - /Applications/MAMP/htdocs/upwork/cloudportal/PORTAL_WHMCS/whmcs:/virtual/cp.dynamic.com/htdocs/whmcs
    exec:
      - mkdir -p /virtual/cp.dynamic.com/htdocs/non-public
      - mkdir -p /virtual/cp.dynamic.com/htdocs/whmcs
      - mkdir -p /virtual/cp.dynamic.com/htdocs/logs
      - touch /virtual/cp.dynamic.com/htdocs/logs/error.log 
      - touch /virtual/cp.dynamic.com/htdocs/logs/access.log
      - rm /etc/nginx/conf.d/default.conf
      - mv /virtual/cp.dynamic.com/htdocs/admin /virtual/cp.dynamic.com/htdocs/pmadci"

  mailhog:
    image: mailhog/mailhog
    container_name: "MAILHOG"
    hostname: mailhog
    restart: always
    networks:
      whmcs:
        ipv4_address: 10.0.1.4
    ports:
      - 8025:8025
      - 1025:1025

networks:
  whmcs:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/29
          gateway: 10.0.1.1
